[project]
name = "stripe-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.9",
    "python-dotenv>=1.2.1",
    "stripe>=14.1.0",
]
